#-------------------------------
# General Site Settings

menu:
- {name: 'Home', url: ''}
- {name: 'Blog',     url: 'blog'}
- {name: 'About',    url: 'about'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: '포토부스 이용 가이드',   url: 'proj-1'}
- {name: '예약 전 확인 사항',   url: 'proj-2'}
- {name: '업로드 예정', url: 'proj-3'}
- {name: '업로드 예정',  url: 'proj-4'}
- {name: '업로드 예정',  url: 'proj-5'}

#-------------------------------
# Contact Section

social:
- {icon: 'linkedin',   link: 'https://litt.ly/blankstudio'}
- {icon: 'instagram', link: 'https://www.instagram.com/blankstudio_photobooth/'}
- {icon: 'vine',  link: 'https://blog.naver.com/blank_studio_'}
- {icon: 'google-plus',  link: 'https://pf.kakao.com/_nxgxeDxj'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'blank studio'
  rel-author: 'https://litt.ly/blankstudio'
  rel-publisher: 'https://litt.ly/blankstudio'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
